In [2]:
import numpy as np
print("NumPy version:", np.__version__)
print("Sab theek hai! ✅")


NumPy version: 2.4.4
Sab theek hai! ✅


In [3]:
# Apne 5 subjects ke marks
my_marks = np.array([85, 90, 78, 92, 88])

print("Meri marks:", my_marks)
print("Shape:", my_marks.shape)
print("Average:", np.mean(my_marks))
print("Highest:", np.max(my_marks))
print("Lowest:", np.min(my_marks))

Meri marks: [85 90 78 92 88]
Shape: (5,)
Average: 86.6
Highest: 92
Lowest: 78


In [4]:
# 3 students, 4 subjects
class_marks = np.array([
    [85, 90, 78, 92],
    [70, 88, 95, 60],
    [91, 75, 83, 87]
])

print("Class Result:\n", class_marks)
print("Shape:", class_marks.shape)
print("Rows:", class_marks.shape[0])
print("Columns:", class_marks.shape[1])


Class Result:
 [[85 90 78 92]
 [70 88 95 60]
 [91 75 83 87]]
Shape: (3, 4)
Rows: 3
Columns: 4


In [ ]:
#TOPIC 1 — Understanding Axis (Very Important!)
#What is an Axis?
#An axis is simply the direction in which NumPy performs an operation. This is one of the most important concepts to understand because you'll use it everywhere—not just in NumPy, but also in Pandas, TensorFlow, and many other data science and machine learning libraries.

import numpy as np

marks = np.array([
    [85, 90, 78],   # Ali    (Math, Sci, Eng)
    [70, 88, 95],   # Sara
    [91, 75, 83]    # Usman
])

# axis=0 → Har COLUMN ka mean (subject wise average)
col_avg = np.mean(marks, axis=0)
print("Har subject ka avg:", col_avg)
# [82.  84.33  85.33]
# Math avg, Science avg, English avg

# axis=1 → Har ROW ka mean (student wise average)
row_avg = np.mean(marks, axis=1)
print("Har student ka avg:", row_avg)
# [84.33  84.33  83.]
# Ali avg, Sara avg, Usman avg

# Bina axis → Poore array ka mean
total_avg = np.mean(marks)
print("Overall avg:", total_avg)  # 83.88

Har subject ka avg: [82.         84.33333333 85.33333333]
Har student ka avg: [84.33333333 84.33333333 83.        ]
Overall avg: 83.88888888888889


In [ ]:
# Topic 2: Broadcasting in NumPy (AI'S secret weapon)

import numpy as np

# ============================================
# CASE 1 — Array + Single Number
# ============================================
arr = np.array([1, 2, 3, 4, 5])

result = arr + 10
print(result)  # [11 12 13 14 15]

# Andar yeh ho raha hai:
# [1,  2,  3,  4,  5]
# +
# [10, 10, 10, 10, 10]  ← 10 broadcast hua!
# =
# [11, 12, 13, 14, 15]

# ============================================
# CASE 2 — 2D Array + 1D Array
# ============================================
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

row = np.array([10, 20, 30])

result2 = matrix + row
print("\nMatrix + Row:\n", result2)
# [[11 22 33]
#  [14 25 36]
#  [17 28 39]]

# Andar yeh hua:
# row = [10, 20, 30] teenon rows pe broadcast hua!

# ============================================
# CASE 3 — Real AI Example
# Normalization (Data 0-1 ke beech karna)
# ============================================
data = np.array([
    [100, 200, 150],
    [300, 250, 180],
    [120, 160, 140]
])

# Har column ka min aur max
col_min = np.min(data, axis=0)
col_max = np.max(data, axis=0)

# Normalize karo — Broadcasting use ho raha hai!
normalized = (data - col_min) / (col_max - col_min)
print("\nNormalized Data:\n", normalized)
# Sab values 0 aur 1 ke beech aa jayengi

[11 12 13 14 15]

Matrix + Row:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

Normalized Data:
 [[0.         0.44444444 0.25      ]
 [1.         1.         1.        ]
 [0.1        0.         0.        ]]


In [ ]:
# TOPIC 3 — Matrix Multiplication (The Heart of Neural Networks!)

#Dot Product vs Element-wise

import numpy as np

# ============================================
# Element-wise Multiplication ( * )
# Both arrays shapes should be same
# ============================================
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

element_wise = a * b
print("Element-wise:", element_wise)
# [4, 10, 18]  ← 1*4, 2*5, 3*6

# ============================================
# Dot Product / Matrix Multiplication ( @ )
# This is the real mutiplication in AI
# ============================================

# Rule: (M x N) dot (N x P) = (M x P)
# Pehli matrix ke COLUMNS = Doosri matrix ke ROWS

A = np.array([
    [1, 2],   # 2x2 matrix
    [3, 4]
])

B = np.array([
    [5, 6],   # 2x2 matrix
    [7, 8]
])

# Method 1 — @ operator (modern way)
result = A @ B
print("\nMatrix Multiplication (A @ B):\n", result)
# [[19 22]
#  [43 50]]

# Method 2 — np.dot() (same work)
result2 = np.dot(A, B)
print("\nnp.dot(A, B):\n", result2)

# Manually verify karo:
# result[0,0] = (1*5) + (2*7) = 5 + 14 = 19 ✅
# result[0,1] = (1*6) + (2*8) = 6 + 16 = 22 ✅

# ============================================
# REAL AI EXAMPLE — Neural Network Layer!
# ============================================
# Input data — 3 samples, 4 features
inputs = np.array([
    [1.0, 2.0, 3.0, 4.0],   # Sample 1
    [5.0, 6.0, 7.0, 8.0],   # Sample 2  
    [9.0, 1.0, 2.0, 3.0],   # Sample 3
])

# Weights — 4 inputs → 3 neurons
weights = np.random.randn(4, 3)

# Bias — har neuron ka ek bias
bias = np.array([0.1, 0.2, 0.3])

# Forward pass — Neural Network ka calculation!
output = inputs @ weights + bias
print("\nNeural Network Output:\n", output)
print("Output Shape:", output.shape)  # (3, 3)
# 3 samples, 3 neurons — yahi AI ka core hai!

Element-wise: [ 4 10 18]

Matrix Multiplication (A @ B):
 [[19 22]
 [43 50]]

np.dot(A, B):
 [[19 22]
 [43 50]]

Neural Network Output:
 [[ -5.02048589  -3.32249678   2.69320626]
 [-11.04523348  -9.18333055   4.62031432]
 [  3.0897922    0.52176335   3.32632155]]
Output Shape: (3, 3)


In [4]:
# TOPIC 4 — Stacking & Splitting

import numpy as np

# ============================================
# STACKING — Arrays ko join karna
# ============================================

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vertical Stack — Upar neeche lagao
v = np.vstack([a, b])
print("vstack:\n", v)
# [[1 2 3]
#  [4 5 6]]

# Horizontal Stack — Side by side lagao
h = np.hstack([a, b])
print("\nhstack:", h)
# [1 2 3 4 5 6]

# Concatenate — Flexible stacking
c0 = np.concatenate([a, b], axis=0)
print("\nconcatenate:", c0)
# [1 2 3 4 5 6]

# 2D stacking
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("\n2D vstack:\n", np.vstack([m1, m2]))
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

print("\n2D hstack:\n", np.hstack([m1, m2]))
# [[1 2 5 6]
#  [3 4 7 8]]

# ============================================
# SPLITTING — Array ko tukdon mein kato
# ============================================
arr = np.array([10, 20, 30, 40, 50, 60])

# 3 equal parts mein kato
parts = np.split(arr, 3)
print("\nSplit into 3:", parts)
# [array([10, 20]), array([30, 40]), array([50, 60])]

# Custom split points pe kato
custom = np.split(arr, [2, 4])
print("Custom split:", custom)
# [array([10, 20]), array([30, 40]), array([50, 60])]

vstack:
 [[1 2 3]
 [4 5 6]]

hstack: [1 2 3 4 5 6]

concatenate: [1 2 3 4 5 6]

2D vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

2D hstack:
 [[1 2 5 6]
 [3 4 7 8]]

Split into 3: [array([10, 20]), array([30, 40]), array([50, 60])]
Custom split: [array([10, 20]), array([30, 40]), array([50, 60])]


In [5]:
# TOPIC 5 — Copy vs View (Tricky Bug!)

import numpy as np

# ============================================
# VIEW — Original se connected hota hai!
# ============================================
original = np.array([1, 2, 3, 4, 5])

view_arr = original[1:4]   # Slice = VIEW hai!
print("Original:", original)   # [1 2 3 4 5]
print("View:", view_arr)       # [2 3 4]

# View change karo
view_arr[0] = 999

print("\nView change karne ke baad:")
print("View:", view_arr)       # [999   3   4]
print("Original:", original)   # [  1 999   3   4   5] ← ORIGINAL BHI BADAL GAYA!

# ============================================
# COPY — Bilkul naya array banta hai
# ============================================
original2 = np.array([1, 2, 3, 4, 5])

copy_arr = original2[1:4].copy()   # .copy() lagao!
copy_arr[0] = 999

print("\nCopy change karne ke baad:")
print("Copy:", copy_arr)         # [999   3   4]
print("Original:", original2)    # [1 2 3 4 5] ← SAFE HAI!

# ============================================
# Kaise check karein — View hai ya Copy?
# ============================================
a = np.array([1, 2, 3])
b = a[:]        # View
c = a.copy()    # Copy

print("\nb ka base:", b.base is a)   # True  → View hai
print("c ka base:", c.base is a)    # False → Copy hai

Original: [1 2 3 4 5]
View: [2 3 4]

View change karne ke baad:
View: [999   3   4]
Original: [  1 999   3   4   5]

Copy change karne ke baad:
Copy: [999   3   4]
Original: [1 2 3 4 5]

b ka base: True
c ka base: False


In [ ]:
#  TOPIC 6 — Fancy Indexing & np.where

import numpy as np

# ============================================
# FANCY INDEXING — Index list se select karo
# ============================================
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Specific indexes select karo
selected = arr[[0, 2, 5]]
print("Fancy Indexing:", selected)  # [10 30 60]

# 2D mein fancy indexing
matrix = np.array([
    [1,  2,  3],
    [4,  5,  6],
    [7,  8,  9],
    [10, 11, 12]
])

# Specific rows lo
rows = matrix[[0, 2, 3]]
print("\nSelected rows:\n", rows)
# [[ 1  2  3]
#  [ 7  8  9]
#  [10 11 12]]

# ============================================
# np.where — Condition based replacement
# AI mein activation functions ke liye use!
# ============================================
scores = np.array([45, 78, 32, 91, 55, 67, 28, 88])

# Condition: 50 se upar = "Pass", neeche = "Fail"
result = np.where(scores >= 50, "Pass", "Fail")
print("\nResults:", result)
# ['Fail' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass']

# Numbers ke saath — Negative values ko 0 kardo (ReLU activation!)
data = np.array([-3, -1, 0, 2, 5, -2, 8])
relu = np.where(data > 0, data, 0)
print("\nReLU output:", relu)
# [0 0 0 2 5 0 8]
# Yahi ReLU activation function hai AI mein!

# ============================================
# np.argmax / np.argmin — Index dhundho
# ============================================
marks = np.array([72, 88, 95, 61, 79, 55, 91])

print("\nHighest mark:", np.max(marks))           # 95
print("Highest mark ka index:", np.argmax(marks)) # 2

print("Lowest mark:", np.min(marks))              # 55
print("Lowest mark ka index:", np.argmin(marks))  # 5

# 💡 Pro Insight:np.where(data > 0, data, 0) __ This is Relu activation function

Fancy Indexing: [10 30 60]

Selected rows:
 [[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]

Results: ['Fail' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass']

ReLU output: [0 0 0 2 5 0 8]

Highest mark: 95
Highest mark ka index: 2
Lowest mark: 55
Lowest mark ka index: 5
