In [3]:
import numpy as np

# ============================================
# PROJECT — Sales Data Analyzer
# Ek real company ka data analyze karo
# ============================================

np.random.seed(42)  # Reproducible results ke liye

# 4 quarters, 6 products ki sales (units)
sales = np.array([
    [150, 230, 180, 290, 120, 95],   # Q1
    [200, 180, 220, 310, 150, 110],  # Q2
    [175, 250, 190, 280, 130, 125],  # Q3
    [220, 270, 240, 350, 160, 140],  # Q4
])

products = ['Laptop', 'Phone', 'Tablet', 'Headphones', 'Charger', "Speaker"]
quarters = ['Q1', 'Q2', 'Q3', 'Q4']

print("=" * 55)
print("         ANNUAL SALES REPORT")
print("=" * 55)

# --- Har product ki total annual sales ---
product_totals = np.sum(sales, axis=0)
print("\n📦 Product wise Annual Sales:")
for i, product in enumerate(products):
    print(f"   {product:12}: {product_totals[i]} units")

# --- Har quarter ki total sales ---
quarter_totals = np.sum(sales, axis=1)
print("\n📅 Quarter wise Total Sales:")
for i, q in enumerate(quarters):
    print(f"   {q}: {quarter_totals[i]} units")

# --- Best performing product ---
best_product_idx = np.argmax(product_totals)
print(f"\n🏆 Best Product: {products[best_product_idx]}")
print(f"   Total Sales: {product_totals[best_product_idx]} units")

# --- Worst performing product ---
worst_idx = np.argmin(product_totals)
print(f"\n⚠️  Needs Attention: {products[worst_idx]}")
print(f"   Total Sales: {product_totals[worst_idx]} units")

# --- Quarter over Quarter growth ---
print("\n📈 Quarter over Quarter Growth:")
for i in range(1, 4):
    growth = ((quarter_totals[i] - quarter_totals[i-1])
              / quarter_totals[i-1] * 100)
    arrow = "↑" if growth > 0 else "↓"
    print(f"   {quarters[i-1]}→{quarters[i]}: {arrow} {growth:.1f}%")

# --- Normalization — 0 to 1 scale ---
normalized = (sales - sales.min()) / (sales.max() - sales.min())
print("\n📊 Normalized Sales (0-1 scale):")
print(np.round(normalized, 2))

# --- High performing cells (above average) ---
avg = np.mean(sales)
high_perf = np.where(sales > avg, sales, 0)
print(f"\n✅ Above Average Sales (avg={avg:.0f}):")
print(high_perf)

         ANNUAL SALES REPORT

📦 Product wise Annual Sales:
   Laptop      : 745 units
   Phone       : 930 units
   Tablet      : 830 units
   Headphones  : 1230 units
   Charger     : 560 units
   Speaker     : 470 units

📅 Quarter wise Total Sales:
   Q1: 1065 units
   Q2: 1170 units
   Q3: 1150 units
   Q4: 1380 units

🏆 Best Product: Headphones
   Total Sales: 1230 units

⚠️  Needs Attention: Speaker
   Total Sales: 470 units

📈 Quarter over Quarter Growth:
   Q1→Q2: ↑ 9.9%
   Q2→Q3: ↓ -1.7%
   Q3→Q4: ↑ 20.0%

📊 Normalized Sales (0-1 scale):
[[0.22 0.53 0.33 0.76 0.1  0.  ]
 [0.41 0.33 0.49 0.84 0.22 0.06]
 [0.31 0.61 0.37 0.73 0.14 0.12]
 [0.49 0.69 0.57 1.   0.25 0.18]]

✅ Above Average Sales (avg=199):
[[  0 230   0 290   0   0]
 [200   0 220 310   0   0]
 [  0 250   0 280   0   0]
 [220 270 240 350   0   0]]


In [ ]:
#  Full Code Explained Line by Line
# Line 1 — Seed

np.random.seed(42)

# np.random.seed(42) means:
# "Generate random numbers
#  but always the SAME ones"

# Every time you use seed(42) —
# you get the exact same random numbers.
# This is done so that
# anyone else running your code
# sees the same results!

# 42 is not a special number —
# you can use any number you want!

#Line 2 — Sales Array

sales = np.array([
    [150, 230, 180, 290, 120, 95],   # Q1
    [200, 180, 220, 310, 150, 110],  # Q2
    [175, 250, 190, 280, 130, 125],  # Q3
    [220, 270, 240, 350, 160, 140],  # Q4
])

# This is a 2D table:

#          Lap  Phone  Tab  Head  Char  Speak
# Q1  →  [ 150,  230,  180,  290,  120,   95 ]
# Q2  →  [ 200,  180,  220,  310,  150,  110 ]
# Q3  →  [ 175,  250,  190,  280,  130,  125 ]
# Q4  →  [ 220,  270,  240,  350,  160,  140 ]

# Shape = (4 rows, 6 columns) = (4, 6)

# Line 3 — Print Header

print("=" * 55)
print("         ANNUAL SALES REPORT")
print("=" * 55)

# "=" * 55 means:
# repeat the "=" sign 55 times

# Output:
# =======================================================
#          ANNUAL SALES REPORT
# =======================================================

# This is just for formatting —
# makes the report look clean and professional!

# Line 4 — Product Totals (axis=0)

product_totals = np.sum(sales, axis=0)

# axis=0 means — go TOP TO BOTTOM (collapse rows)
# Calculate sum of each COLUMN

#          Lap   Phone  Tab   Head  Char  Speak
# Q1  →  [ 150,  230,  180,  290,  120,   95 ]
# Q2  →  [ 200,  180,  220,  310,  150,  110 ]  ← all rows
# Q3  →  [ 175,  250,  190,  280,  130,  125 ]     get
# Q4  →  [ 220,  270,  240,  350,  160,  140 ]     added
#          ↓     ↓     ↓     ↓     ↓     ↓
#        [745,  930,  830, 1230,  560,  470]

# Laptop total    = 150+200+175+220 = 745
# Phone total     = 230+180+250+270 = 930
# Headphones total= 290+310+280+350 = 1230  ← highest!

# Line 5 — Enumerate Loop

for i, product in enumerate(products):
    print(f"   {product:12}: {product_totals[i]} units")

#     What does enumerate() do?
# It gives you a COUNTER along with the list!

# enumerate(['Laptop','Phone','Tablet'])
# → (0, 'Laptop')
# → (1, 'Phone')
# → (2, 'Tablet')

# i       = number  (0, 1, 2, 3...)
# product = name    (Laptop, Phone...)

# {product:12} means:
# print product name in exactly
# 12 characters of space
# so everything stays aligned!

# Output:
#    Laptop      : 745 units
#    Phone       : 930 units
#    Tablet      : 830 units

# Line 6 — Quarter Totals (axis=1)

# quarter_totals = np.sum(sales, axis=1)

# axis=1 means — go LEFT TO RIGHT (collapse columns)
# Calculate sum of each ROW

#          Lap   Phone  Tab   Head  Char  Speak   SUM
# Q1  →  [ 150,  230,  180,  290,  120,   95 ] = 1065
# Q2  →  [ 200,  180,  220,  310,  150,  110 ] = 1170
# Q3  →  [ 175,  250,  190,  280,  130,  125 ] = 1150
# Q4  →  [ 220,  270,  240,  350,  160,  140 ] = 1380

# quarter_totals = [1065, 1170, 1150, 1380]

# Line 7 — Best Product

best_product_idx = np.argmax(product_totals)
print(f"\n🏆 Best Product: {products[best_product_idx]}")

# product_totals = [745, 930, 830, 1230, 560, 470]
#                    0    1    2    3      4    5

# # np.argmax() → returns the INDEX of the largest value
# #             → 1230 is the largest → index is 3

# # best_product_idx = 3

# # products[3] = 'Headphones'

# # Output:
# # 🏆 Best Product: Headphones
# #    Total Sales: 1230 units

# Line 8 — Quarter Growth

# for i in range(1, 4):
#     growth = ((quarter_totals[i] - quarter_totals[i-1])
#               / quarter_totals[i-1] * 100)
#     arrow = "↑" if growth > 0 else "↓"
#     print(f"   {quarters[i-1]}→{quarters[i]}: {arrow} {growth:.1f}%")

#     range(1, 4) → [1, 2, 3]

# When i=1:
#   quarter_totals[1] = 1170  (Q2)
#   quarter_totals[0] = 1065  (Q1)

#   growth = (1170 - 1065) / 1065 * 100
#          = 105 / 1065 * 100
#          = 9.8%

#   arrow = "↑" (because growth is positive)

#   Output: Q1→Q2: ↑ 9.8%

# This formula is PERCENTAGE CHANGE:
#   (new - old) / old × 100

# {growth:.1f}% means:
#   show growth with only 1 decimal place

# Line 9 — Normalization

normalized = (sales - sales.min()) / (sales.max() - sales.min())
print(np.round(normalized, 2))

# What is Normalization?
# Bringing all values between 0 and 1!

# Why? AI models struggle with raw numbers.
# One value is 1000, another is 5 —
# the model gets confused!
# Normalize them and everything is equal!

# Formula:
#   (value - minimum) / (maximum - minimum)

# sales.min() = 95   (smallest number)
# sales.max() = 350  (largest number)

# 95 normalized:
#   (95  - 95) / (350 - 95) = 0/255 = 0.0

# 350 normalized:
#   (350 - 95) / (350 - 95) = 255/255 = 1.0

# Everything else falls between 0 and 1!

# np.round(normalized, 2)
# → round to 2 decimal places

# Line 10 — np.where

# avg = np.mean(sales)
# high_perf = np.where(sales > avg, sales, 0)

# np.mean(sales) → average of the entire table

# np.where(CONDITION, VALUE_IF_TRUE, VALUE_IF_FALSE)

# np.where(sales > avg, sales, 0)
# means:
#   "If a cell's value is greater
#    than average → keep that value
#    If it is below average → make it 0"

# Example:
#   avg = 196
#   150 > 196? No  → 0
#   230 > 196? Yes → 230
#   310 > 196? Yes → 310
#   120 > 196? No  → 0

# 🧠 Remember Everything in One Place

# shape[0]   = rows       = quarters  = axis=0 (top to bottom)
# shape[1]   = columns    = products  = axis=1 (left to right)
# argmax()   = index of the largest value
# argmin()   = index of the smallest value
# enumerate  = list + counter together
# np.where   = if/else applied on entire array
# normalize  = all values scaled between 0 and 1



         ANNUAL SALES REPORT
   Laptop      : 745 units
   Phone       : 930 units
   Tablet      : 830 units
   Headphones  : 1230 units
   Charger     : 560 units
   Speaker     : 470 units
